import type { NextPage } from 'next'
import Head from 'next/head'
import AddTodoForm from '../components/AddTodoForm'
import TodoList from '../components/TodoList'
import Todo from '../components/Todo'

const Home: NextPage = () => {
  return (
    <div className={`container`}>

      <Head>
        <title>Querplex Todo CRUD Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`main`}>

        <h1 className={`title`}>
          Todo List
        </h1>

        <AddTodoForm />

        <TodoList>

          <Todo />

        </TodoList>

      </main>

      <footer className={`footer`}>
      </footer>
    </div>
  )
}

export default Home
