import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className={`container`}>
      <Head>
        <title>Querplex Todo CRUD Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`main`}>

        <h1 className={`title`}>
          Todo List
        </h1>

        <p className={`description`}>
          <input 
            type="text"
            aria-label='AddTodo'
            value={`What needs to get done`}
          />
          <button
            aria-label='SubmitTodo'
          >
            Add
          </button>
        </p>

        <div className={`card`}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
        </div>
      
      </main>

      <footer className={`footer`}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={`logo`}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
